### ISSUE TITLE
PROXY環境下で起動したコンテナから外部ネットワークにアクセスできない

### ISSUE THREAD

**Issue by k0inoue** [p-robotics-hub/burger_war_dev#4]
PROXY環境下では起動したコンテナから外部ネットワークにアクセスできずに、  
`apt-get`などで通信エラーが出ます。

`docker run`時にホストで定義されたPROXYの環境変数(`HTTPS_PROXY`など)を渡せば  
`apt-get`なども問題なく使えるようになりますが、`sim_with_judge.sh`を実行した際に、
以下のエラーが出て、審判サーバの起動に失敗するようになります。

```
Traceback (most recent call last):
  File "/home/developer/catkin_ws/src/burger_war_kit/burger_war/scripts/sendIdToJudge.py", line 137, in <module>
    state_publisher.publishWarState()
  File "/home/developer/catkin_ws/src/burger_war_kit/burger_war/scripts/sendIdToJudge.py", line 115, in publishWarState
    resp = requests.get(self.judge_url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 76, in get
    return request('※get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/pyth※ **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='server.address', port=server.port): Max retries exceeded with url: http://host.address (Caused by ProxyError('Cannot connect to proxy.', error(104, 'Connection reset by peer')))
```

※エラーログ中のPROXYアドレスやポート番号などは実際の設定値を書き換えています

**Comment by seigot** [comment]
/dev/environment以下にHTTPS_PROXYなど書いても解決するかもしれないですー

**Comment by seigot** [comment]
むりやりだと以下で環境変数を削除して解決できそうです

```
unset HTTP_PROXY
unset HTTPS_PROXY
unset http_proxy
unset https_proxy
```

 ■git操作もプロキシ設定が必要かもしれません

```
$ git pull
Could not resolve host: github.com
git pull用のプロキシ設定も必要
（参考）https://github.com/desktop/desktop/issues/4872
git config --global http.proxy http://xxx.xxx.xxx.xxx:yyy

※xxx.xxx.xxx.xxx:yyyはIPアドレスとポート番号
```

■Dockerの中からネットワークアクセスするためのプロキシ設定が必要かもしれません

```
$ cat /etc/environment
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
http_proxy="http://xxx.xxx.xxx.xxx:yyy/"
https_proxy="https://xxx.xxx.xxx.xxx:yyy/"
ftp_proxy="ftp://xxx.xxx.xxx.xxx:yyy/"
socks_proxy="socks://xxx.xxx.xxx.xxx:yyy/"
```

```
$ sudo apt-get update
```


■ブラウザからもプロキシ設定が必要かもしれません

```
firefoxで設定する場合
設定⇒proxy設定とか
```

**Comment by k0inoue** [comment]
@seigot 
ご助言頂きありがとうございます。
環境変数のno_proxyを定義して、アクセス先がローカルホストの場合は
PROXY対象外とすることで本件対応致しました。

[補足：PROXYの設定について](https://github.com/p-robotics-hub/burger_war_dev/blob/main/STARTUP_GUIDE.md#c-proxy%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)
